name: Deploy to Nexus
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set Up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Maven-Settings
        uses: s4u/maven-settings-action@v2.6.0
        with:
          servers: '[{"id": "rytrox-nexus", "username": "${{ secrets.NEXUS_USERNAME }}", "password": "${{ secrets.NEXUS_PASSWORD }}"}]'
      - name: Setup Spigot
        uses: SpraxDev/Action-SpigotMC@v4.0.0
        with:
          versions: 1.18.2
          remapped: true
          generateSrc: false
          generateDoc: false
          disableJavaCheck: false
          buildToolProvider: SpigotMC
      - name: Deploy
        run: mvn deploy
