name: Deploy to Nexus
on:
  release:
    types:
      - released

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set Up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven
      - name: Maven-Settings
        uses: s4u/maven-settings-action@v2.6.0
        with:
          servers: |
            [
              {
                "id": "nexus", 
                "username": "${{ secrets.NEXUS_USERNAME }}", 
                "password": "${{ secrets.NEXUS_PASSWORD }}"
              },
              {
                "id": "nexus-snapshots",
                "username": "${{ secrets.NEXUS_USERNAME }}",
                "password": "${{ secrets.NEXUS_PASSWORD }}"
              }
            ]
          githubServer: false
      - name: Setup Spigot (normal)
        uses: SpraxDev(Action-SpigotMC@v4.1.0
        with:
          versions: 1.8.8
          generateSrc: false
          generateDoc: false
          disableJavaCheck: true
          buildToolProvider: SpigotMC
      - name: Setup Spigot (remapped)
        uses: SpraxDev/Action-SpigotMC@v4.0.0
        with:
          versions: 1.19.2, 1.18.2
          remapped: true
          generateSrc: false
          generateDoc: false
          disableJavaCheck: false
          buildToolProvider: SpigotMC
      - name: Debug load settings.xml
        uses: actions/upload-artifact@v3
        with:
          name: settings-xml
          path: /home/runner/.m2/settings.xml
      - name: Deploy
        run: mvn deploy
