name: Deploy to Nexus (1.8 - Java 8)
on:
  release:
    types:
      - released

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set Up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: maven
      - name: Maven-Settings
        uses: s4u/maven-settings-action@v2.6.0
        with:
          servers: |
            [
              {
                "id": "nexus", 
                "username": "${{ secrets.NEXUS_USERNAME }}", 
                "password": "${{ secrets.NEXUS_PASSWORD }}"
              },
              {
                "id": "nexus-snapshots",
                "username": "${{ secrets.NEXUS_USERNAME }}",
                "password": "${{ secrets.NEXUS_PASSWORD }}"
              }
            ]
          githubServer: false
      - name: Setup Spigot
        uses: SpraxDev/Action-SpigotMC@v4.0.0
        with:
          versions: 1.8.8
          remapped: false
          generateSrc: false
          generateDoc: false
          disableJavaCheck: false
          buildToolProvider: SpigotMC
      - name: Debug load settings.xml
        uses: actions/upload-artifact@v3
        with:
          name: settings-xml
          path: /home/runner/.m2/settings.xml
      - name: Deploy
        run: mvn -pl core,1.8 -am deploy
