name: Release
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: Log Level
        required: true
        default: warning

jobs:
  release:
    needs:
      - coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven
      - name: Setup Spigot
        uses: SpraxDev/Action-SpigotMC@v4.0.0
        with:
          versions: 1.18.2
          remapped: true
          generateSrc: false
          generateDoc: false
          disableJavaCheck: false
          buildToolProvider: SpigotMC
      - name: Release to Maven
        run: mvn deploy
