name: Test & Build
on: push

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set Up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven
      - name: Setup Spigot
        uses: SpraxDev/Action-SpigotMC@v3
        with:
          versions: 1.18.1
          generateSrc: false
          generateDoc: false
          disableJavaCheck: false
          buildToolProvider: SpigotMC
      - name: Build
        run: mvn clean package
      - name: Test
        run: mvn test jacoco:report
      - name: jacoco-badge-generator
        uses: cicirello/jacoco-badge-generator@v2.5.0
        with:
          generate-branches-badge: true
