name: Test & Build
on: push

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set Up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven
      - name: Build
        run: mvn clean package
      - name: Test
        run: mvn test
